language: elixir
elixir:
  - 1.6.3
otp_release:
  - 20.0
services: docker
sudo: false
before_install:
    - docker run -d --name clickhouse-server --ulimit nofile=262144:262144 -p 8123:8123 yandex/clickhouse-server
script: "mix test"
